import Head from 'next/head'
import Link from 'next/link'
import Layout from '../components/layout'
import styles from '../styles/Home.module.css'

import useAccount from '../lib/useAccount'

const Home = () => {

    const { account } = useAccount()

    return <Layout>
        <div>
            <Head>
                <title>COVID-19 VDAS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h2 className={styles.title}>
                    Welcome to VDAS
                </h2>

                <p className={styles.description}>
                    COVID-19 Violation Detection Assistance System
                </p>

                {!account?.isLoggedIn &&
                    <div className={styles.grid}>
                        <Link href="/login">
                            <button className="btn btn-primary px-4 py-2 fs-5">
                                <i className="bi bi-person me-2" /> LOGIN
                            </button>
                        </Link>
                    </div>
                }
            </main>
        </div>
    </Layout>
}

export default Home